### ISSUE TITLE
Make it more user-friendly

### ISSUE THREAD

**Issue by sergeevabc** [wfxr/csview#8]
``` console
$ echo Name;Age;Sex; > test.csv

$ csview.exe test.csv
++
||
++
++

(checking manual…)

$ csview.exe  -d ; test.csv
++
||
++
++

(wtf…)

$ csview.exe -d ; -H test.csv
+------+-----+------+ 
| Name | Age | Sex  | 
+------+-----+------+ 

(at last!)
```

1. Reverse `-H` not to confuse newcomer with no data displayed, or at least don’t require it in case of single line.

2. Make `csview` smarter in terms of recognizing common [delimiters][1] (for example, check [this][2] and [that][3]),
because comma is often used as decimal separator or even as is in cases like “Pancakes;0,2kcal;Use flour, milk, eggs, honey”.

[1]: https://en.wikipedia.org/wiki/Delimiter-separated_values
[2]: https://lemonunit.github.io/csv-editor-online/
[3]: https://projectcsv.github.io/

**Comment by wfxr** [comment]
Thanks for your feedback. 

> Reverse -H not to confuse newcomer with no data displayed, or at least don’t require it in case of single line.

The problem you described is actually a bug existed in a crate which `csview` depends on. The header was wrongly omited when the table is empty. `-H/--no-headers` should work the same as the manual describes: tell csview the input has no header row. I fixed it temporarily by a patch.

```
$ echo 'Name;Age;Sex' | csview -d';' -H
+------+-----+-----+
| Name | Age | Sex |
+------+-----+-----+
```

> Make csview smarter in terms of recognizing common delimiters (for example, check this and that),
because comma is often used as decimal separator or even as is in cases like “Pancakes;0,2kcal;Use flour, milk, eggs, honey”.

There is no silver bullet. Think of the following input:
```
a,b;c,d;e
```
```
a|b;c,d
```
```
a<tab>b;c<tab>d
```
Maybe someone thinks that a priority can be assigned to every possible seperators to make guesses. But such a solution is too complicated and still cannot meet everyone's needs. So I prefer keeping it simple and prief. Specify it explicitly if a seperator other than comma is needed since it's not that hard to do.

**Comment by sergeevabc** [comment]
>  Specify it explicitly if a seperator other than comma is needed since it's not that hard to do.

`;` is needed, yes.
